cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://dias.com.br

file:
  upload-dir: /Usuário/Área de trabalho/Programação/Api RestFull - Leandro

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_spring_java?useTimezone=true&serverTimezone=UTC
    username: root
    password: ${DATABASE_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      show-sql: true
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

springdoc:
  pathsToMatch:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true

security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000