name: Continuous Integration with Github Actions

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
          
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Build application JAR
      working-directory: ./
      run: mvn clean package
        
    - name: Build with Maven
      working-directory: ./
      run: docker compose build

    - name: Push to Docker Hub Container Registry
      run: docker tag  ${{ secrets.DOCKER_USERNAME }}/rest-spring-java:latest  ${{ secrets.DOCKER_USERNAME }}/rest-spring-java:${{ github.run_id }}

           docker push ${{ secrets.DOCKER_USERNAME }}/rest-spring-java:${{ github.run_id }}
           docker push ${{ secrets.DOCKER_USERNAME }}/rest-spring-java:latest
   
